apiVersion: apps/v1
kind: Deployment
metadata:
  name: menuitemwebapi-deployment
  labels:
    app: MenuItemWebApi
spec:
  replicas: 1,
  selector:
    matchLabels:
        app: MenuItemWebApi
  template: 
    metadata: 
        labels: 
            app: MenuItemWebApi
    spec: 
        containers: 
        - name: cloudpracticecheck
          image: cloudpracticecheck.azurecr.io/cloudpracticecheckmenuitem:latest
          ports: 
          - containerPort: 8080
        imagePullSecrets:
        - name: menuitemsvcsecret
---
apiVersion: v1
kind: Service
metadata: 
    name: menuitemwebapisvc
spec: 
    type: LoadBalancer
    ports: 
    - port: 80
    selector:
        app : MenuItemWebApi
